# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vget < Formula
  desc "Media downloader CLI for various platforms"
  homepage "https://github.com/guiyumin/vget"
  version "0.13.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/guiyumin/vget/releases/download/v0.13.2/vget_0.13.2_darwin_amd64.zip"
      sha256 "9aecadc7807b449f506dd56422abd739de8faeacd4d3bc2c41fce9c4dcb39902"

      define_method(:install) do
        bin.install "vget"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/guiyumin/vget/releases/download/v0.13.2/vget_0.13.2_darwin_arm64.zip"
      sha256 "b0e3074e527564bb0ea4e0448b415fe7ed50b6163574829988f3d9b133e90dae"

      define_method(:install) do
        bin.install "vget"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/guiyumin/vget/releases/download/v0.13.2/vget_0.13.2_linux_amd64.zip"
      sha256 "ae3d8340623f6c19ad45c465d97f45c6de0ccc81f77ee15fe33dbb0ad6d67234"
      define_method(:install) do
        bin.install "vget"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/guiyumin/vget/releases/download/v0.13.2/vget_0.13.2_linux_arm64.zip"
      sha256 "d5f53a8e4cfdc4c4c0ac915d6ad43cd8d0fc5596c55b3db7d97211e350bd68cc"
      define_method(:install) do
        bin.install "vget"
      end
    end
  end
end
