# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vget < Formula
  desc "Media downloader CLI for various platforms"
  homepage "https://github.com/guiyumin/vget"
  version "0.10.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/guiyumin/vget/releases/download/v0.10.4/vget_0.10.4_darwin_amd64.zip"
      sha256 "df93fc8b2af2b3844fcdacaeef3500161f5cb26c8d5d08d1d6f9844f44bbf842"

      def install
        bin.install "vget"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/guiyumin/vget/releases/download/v0.10.4/vget_0.10.4_darwin_arm64.zip"
      sha256 "4851e9adb378b42873597f123974cefa8c77116819649af2c40405f2251f6b96"

      def install
        bin.install "vget"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/guiyumin/vget/releases/download/v0.10.4/vget_0.10.4_linux_amd64.zip"
      sha256 "09a4498c2a78426193c838355048cfd589fdf32d32f6678fe387cd432b9bb758"
      def install
        bin.install "vget"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/guiyumin/vget/releases/download/v0.10.4/vget_0.10.4_linux_arm64.zip"
      sha256 "00aaddb6bd1f9f78e11dbf937e4ae756fcc78475b5a45ec4c12dec42ed2f1cbb"
      def install
        bin.install "vget"
      end
    end
  end
end
