# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vget < Formula
  desc "Media downloader CLI for various platforms"
  homepage "https://github.com/guiyumin/vget"
  version "0.11.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/guiyumin/vget/releases/download/v0.11.2/vget_0.11.2_darwin_amd64.zip"
      sha256 "07bd4958ad0731c476faf37233ad9ad5971695be77bb96b76081db72e842d225"

      def install
        bin.install "vget"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/guiyumin/vget/releases/download/v0.11.2/vget_0.11.2_darwin_arm64.zip"
      sha256 "9f6ba820fbf37815039c4c28d17d9d769074394245381ed865c313f175f7d468"

      def install
        bin.install "vget"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/guiyumin/vget/releases/download/v0.11.2/vget_0.11.2_linux_amd64.zip"
      sha256 "7426db2fde9904d905e460b3ef1d8ebcc1e8258fd3c6abfe85088b0a3ed72b8e"
      def install
        bin.install "vget"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/guiyumin/vget/releases/download/v0.11.2/vget_0.11.2_linux_arm64.zip"
      sha256 "2ed9516435a2efffd8dcfacbfc2d94e005a808420ee72a3ab19a0403f7a8b38d"
      def install
        bin.install "vget"
      end
    end
  end
end
